# Generated by Django 2.2.4 on 2019-08-20 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Harness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_year', models.IntegerField()),
                ('uid', models.IntegerField(max_length=10, verbose_name='UID')),
                ('notes', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_year', models.IntegerField()),
                ('uid', models.IntegerField(max_length=10, verbose_name='UID')),
                ('notes', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('on_loan', models.IntegerField(max_length=10)),
                ('in_store', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_year', models.IntegerField()),
                ('diameter', models.IntegerField(max_length=2, verbose_name='Diameter (mm)')),
                ('length', models.IntegerField(max_length=3, verbose_name='Length (m)')),
                ('notes', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SRTKit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_code', models.CharField(default='Purple & ', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignOutOtherGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=3)),
                ('signed_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gear.OtherGear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignInOtherGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=3)),
                ('signed_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gear.OtherGear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HireSRTKit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('signed_in', models.DateTimeField(blank=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gear.SRTKit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HireRope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('signed_in', models.DateTimeField(blank=True)),
                ('rope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gear.Rope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HireHelmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('signed_in', models.DateTimeField(blank=True)),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gear.Helmet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HireHarness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('signed_in', models.DateTimeField(blank=True)),
                ('harness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gear.Harness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
