# Generated by Django 2.2.4 on 2019-08-20 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gear', '0002_auto_20190820_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signinothergear',
            old_name='user',
            new_name='signed_in_by',
        ),
        migrations.RenameField(
            model_name='signoutothergear',
            old_name='user',
            new_name='signed_out_by',
        ),
        migrations.RemoveField(
            model_name='hireharness',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hirehelmet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hirerope',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hiresrtkit',
            name='user',
        ),
        migrations.AddField(
            model_name='hireharness',
            name='signed_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hireharness',
            name='signed_out_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hireharnessigned_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hirehelmet',
            name='signed_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hirehelmet',
            name='signed_out_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hirehelmetigned_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hirerope',
            name='signed_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hirerope',
            name='signed_out_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hireropeigned_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hiresrtkit',
            name='signed_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hiresrtkit',
            name='signed_out_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiresrtkitigned_out', to=settings.AUTH_USER_MODEL),
        ),
    ]
