# Generated by Django 2.2.4 on 2019-08-20 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gear', '0003_auto_20190820_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireharness',
            name='signed_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirehelmet',
            name='signed_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirerope',
            name='signed_in_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hirerope',
            name='signed_out_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hireropeigned_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hiresrtkit',
            name='signed_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
