# Generated by Django 2.2.4 on 2019-08-20 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gear', '0004_auto_20190820_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerope',
            name='signed_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirerope',
            name='signed_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
