# Generated by Django 2.2.3 on 2019-08-21 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gear', '0006_auto_20190820_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oversuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='UID')),
                ('size', models.CharField(max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Undersuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='UID')),
                ('size', models.CharField(max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HireUndersuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('signed_in', models.DateTimeField(blank=True, null=True)),
                ('signed_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('signed_out_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hireundersuitigned_out', to=settings.AUTH_USER_MODEL)),
                ('undersuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gear.Undersuit')),
            ],
        ),
        migrations.CreateModel(
            name='HireOversuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('signed_in', models.DateTimeField(blank=True, null=True)),
                ('oversuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gear.Oversuit')),
                ('signed_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('signed_out_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hireoversuitigned_out', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
