# Generated by Django 2.2.3 on 2019-08-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gear', '0008_remove_othergear_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othergear',
            name='in_store',
        ),
        migrations.AddField(
            model_name='othergear',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
