# Generated by Django 2.2.3 on 2019-08-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gear', '0009_auto_20190821_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='othergear',
            name='available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
