# Generated by Django 2.2.4 on 2019-08-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gear', '0010_othergear_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireharness',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hirehelmet',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hireoversuit',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hirerope',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hiresrtkit',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hireundersuit',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='othergear',
            name='available',
            field=models.IntegerField(default=models.IntegerField()),
        ),
        migrations.AlterField(
            model_name='othergear',
            name='on_loan',
            field=models.IntegerField(default=0),
        ),
    ]
