# Generated by Django 2.2.4 on 2019-08-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gear', '0012_auto_20190821_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('hire_self', 'Can hire rope on their own behalf'), ('hire_other', 'Can hire rope on behalf of others')),
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='hirerope',
            options={},
        ),
    ]
