# Generated by Django 2.2.4 on 2019-08-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gear', '0013_auto_20190821_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiresupport',
            options={'managed': False, 'permissions': [('hire_self', 'Can hire gear on their own behalf'), ('hire_other', 'Can hire gear on behalf of others')]},
        ),
    ]
