# Generated by Django 2.2.4 on 2019-08-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gear', '0015_auto_20190822_1108'),
        ('Gear', '0015_auto_20190821_1507'),
    ]

    operations = [
    ]
