# Generated by Django 2.2.4 on 2019-08-22 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_virtual', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(choices=[('expense_claim', 'Expense Claim'), ('charge', 'Charge'), ('grant', 'Grant'), ('reimbursement', 'Reimbursement'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('uncategorised', 'Uncategorised'), ('correctional', 'Correctional')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bank.Account')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_a', to='Bank.Transaction')),
                ('transaction_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_b', to='Bank.Transaction')),
            ],
        ),
    ]
