# Generated by Django 2.2.4 on 2019-08-22 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_auto_20190822_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
