# Generated by Django 2.2.4 on 2019-08-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0006_auto_20190822_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_key',
            field=models.CharField(default='0835042adc0d4c5f92c8aa7e2bae7790', editable=False, max_length=32),
        ),
    ]
