# Generated by Django 2.2.4 on 2019-08-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0007_auto_20190822_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_key',
            field=models.CharField(default='916f38ee343f43d0bd42e66b3db32b8a', editable=False, max_length=32),
        ),
    ]
