# Generated by Django 2.2.4 on 2019-08-22 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0009_auto_20190822_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
