# Generated by Django 2.2.3 on 2019-08-24 17:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0010_auto_20190822_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('credit_a', models.DecimalField(decimal_places=2, max_digits=7)),
                ('credit_b', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_virtual',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='notes',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Bank', 'Bank'), ('User', 'User'), ('Pool', 'Pool')], default='User', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TransactionPair',
        ),
        migrations.AddField(
            model_name='transactiongroup',
            name='transaction_set',
            field=models.ManyToManyField(blank=True, null=True, to='Bank.Transaction'),
        ),
        migrations.AddField(
            model_name='entry',
            name='account_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacton_set_a', to='Bank.Account'),
        ),
        migrations.AddField(
            model_name='entry',
            name='account_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_set_b', to='Bank.Account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='entry_set',
            field=models.ManyToManyField(blank=True, null=True, to='Bank.Entry'),
        ),
    ]
