# Generated by Django 2.2.3 on 2019-08-26 09:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bank', '0011_auto_20190824_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='transactiongroup',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, help_text='If account is unowned, please give it a sensible name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.OneToOneField(blank=True, help_text='If account is to be owned by a person, please select that user here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='entry_set',
            field=models.ManyToManyField(blank=True, editable=False, null=True, to='Bank.Entry'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transactiongroup',
            name='group_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='EventFeeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('CustomCurrencies', models.ManyToManyField(blank=True, null=True, to='Bank.CustomCurrency')),
                ('pools', models.ManyToManyField(blank=True, null=True, to='Bank.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('transaction_group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Bank.TransactionGroup')),
                ('users', models.ManyToManyField(blank=True, null=True, to='Bank.Account')),
            ],
        ),
        migrations.AddField(
            model_name='customcurrency',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bank.Account'),
        ),
    ]
