# Generated by Django 2.2.3 on 2019-08-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0013_auto_20190826_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='entry_set',
        ),
        migrations.RemoveField(
            model_name='transactiongroup',
            name='transaction_set',
        ),
        migrations.AddField(
            model_name='entry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Bank.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Bank.TransactionGroup'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='account_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_set_a', to='Bank.Account'),
        ),
    ]
