# Generated by Django 2.2.3 on 2019-08-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0015_auto_20190826_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactiongroup',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
    ]
