# Generated by Django 2.2.3 on 2019-08-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0016_auto_20190826_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Bank.EventFeeTemplate'),
        ),
    ]
