# Generated by Django 2.2.3 on 2019-08-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0017_event_fee_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
    ]
