# Generated by Django 2.2.4 on 2019-08-27 14:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bank', '0019_auto_20190827_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_event_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='approved_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='open',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_approved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_editable',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_editable',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_approved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_editable',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='transactiongroup',
            name='is_approved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='transactiongroup',
            name='is_editable',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
