# Generated by Django 2.2.4 on 2019-08-27 17:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0021_remove_account_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('banks', models.ManyToManyField(blank=True, null=True, related_name='fee_template_bank_set', to='Bank.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='customcurrency',
            name='credit',
            field=models.DecimalField(decimal_places=2, help_text='The value of this currency in GBP. For a currency that will be a debit (charge), enter a negative number. For a currency that will be a credit, enter a positive number.', max_digits=7),
        ),
        migrations.AlterField(
            model_name='event',
            name='fee_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Bank.FeeTemplate'),
        ),
        migrations.DeleteModel(
            name='EventFeeTemplate',
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='custom_currency',
            field=models.ManyToManyField(blank=True, null=True, to='Bank.CustomCurrency'),
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='pools',
            field=models.ManyToManyField(blank=True, null=True, related_name='fee_template_pool_set', to='Bank.Account'),
        ),
    ]
