# Generated by Django 2.2.4 on 2019-08-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0022_auto_20190827_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
