# Generated by Django 2.2.4 on 2019-08-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0023_event_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='custom_currency',
            field=models.BooleanField(default=False),
        ),
    ]
