# Generated by Django 2.2.4 on 2019-08-28 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0026_remove_entry_custom_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='custom_currency',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='Bank.CustomCurrency'),
        ),
    ]
