# Generated by Django 2.2.4 on 2019-08-28 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0027_entry_custom_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='approved_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='approved_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, to='Bank.Account'),
        ),
        migrations.AlterField(
            model_name='feetemplate',
            name='banks',
            field=models.ManyToManyField(blank=True, related_name='fee_template_bank_set', to='Bank.Account'),
        ),
        migrations.AlterField(
            model_name='feetemplate',
            name='custom_currency',
            field=models.ManyToManyField(blank=True, to='Bank.CustomCurrency'),
        ),
        migrations.AlterField(
            model_name='feetemplate',
            name='pools',
            field=models.ManyToManyField(blank=True, related_name='fee_template_pool_set', to='Bank.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='approved_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='transactiongroup',
            name='approved_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
    ]
