# Generated by Django 2.2.4 on 2019-08-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0028_auto_20190828_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='transaction_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event', to='Bank.TransactionGroup'),
        ),
    ]
