# Generated by Django 2.2.4 on 2019-08-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0031_auto_20190829_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_own__account', 'Can view own account'), ('view_other__account', "Can view others' accounts")]},
        ),
        migrations.AlterModelOptions(
            name='transactiongroup',
            options={'permissions': [('approve__transactiongroup', 'Can approve transaction groups')]},
        ),
    ]
