# Generated by Django 2.2.4 on 2019-08-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0032_auto_20190829_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sort_name',
            field=models.CharField(default='-', editable=False, max_length=100),
        ),
    ]
