# Generated by Django 2.2.4 on 2019-08-30 10:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0036_auto_20190830_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bank.Account')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='custom_expense',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='Bank.CustomExpense'),
        ),
    ]
