# Generated by Django 2.2.4 on 2019-08-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0037_auto_20190830_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feetemplate',
            name='banks',
        ),
        migrations.RemoveField(
            model_name='feetemplate',
            name='pools',
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='custom_expense',
            field=models.ManyToManyField(blank=True, to='Bank.CustomExpense'),
        ),
    ]
