# Generated by Django 2.2.4 on 2019-08-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0003_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='8f5472685b9f4449bb570cb13606c535', max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.TextField(max_length=50),
        ),
    ]
