# Generated by Django 2.2.4 on 2019-08-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0004_auto_20190816_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='0758f29548fc4a58b6e94d5f75a20222', max_length=20),
        ),
    ]
