# Generated by Django 2.2.3 on 2019-08-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0008_auto_20190816_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='c9209c9b2c0e4ee6bcb06c9e5e110ab6', max_length=32),
        ),
    ]
