# Generated by Django 2.2.3 on 2019-08-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0010_auto_20190816_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tape_colour_1',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('red', 'RED'), ('orange', 'ORANGE'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('purple', 'PURPLE'), ('grey', 'GREY'), ('white', 'WHITE'), ('earth', 'EARTH'), ('other', 'OTHER')], default='', max_length=6, verbose_name='Gear Tape Colour 1'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tape_colour_2',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('red', 'RED'), ('orange', 'ORANGE'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('purple', 'PURPLE'), ('grey', 'GREY'), ('white', 'WHITE'), ('earth', 'EARTH'), ('other', 'OTHER')], default='', max_length=6, verbose_name='Gear Tape Colour 2'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tape_colour_3',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('red', 'RED'), ('orange', 'ORANGE'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('purple', 'PURPLE'), ('grey', 'GREY'), ('white', 'WHITE'), ('earth', 'EARTH'), ('other', 'OTHER')], default='', max_length=6, verbose_name='Gear Tape Colour 3'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tape_colour_notes',
            field=models.CharField(blank=True, max_length=50, verbose_name='Gear Tape Notes'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='e1ff4b9530db444c8747b5380e82448a', max_length=32),
        ),
    ]
