# Generated by Django 2.2.3 on 2019-08-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0012_auto_20190817_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rank',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.CharField(choices=[('Member', 'MEMBER'), ('President', 'PRESIDENT'), ('Senior Treasurer', 'SENIOR TREASURER'), ('Junior Treasurer', 'JUNIOR TREASURER'), ('Secretary', 'SECRETARY'), ('Tackle Master', 'TACKLE MASTER'), ('Meets Secretary', 'MEETS SECRETARY'), ('Social Secretary', 'SOCIAL SECRETARY')], default='Member', max_length=30, verbose_name='Club Position'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='b0ec884a21e94e6cafcf83d1843147a9', max_length=32),
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
