# Generated by Django 2.2.3 on 2019-08-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0014_auto_20190817_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tape_colour_1',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('red', 'RED'), ('orange', 'ORANGE'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('purple', 'PURPLE'), ('grey', 'GREY'), ('white', 'WHITE'), ('warth', 'EARTH'), ('other', 'OTHER')], default='', max_length=6, verbose_name='Gear Tape Colour 1'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tape_colour_2',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('red', 'RED'), ('orange', 'ORANGE'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('purple', 'PURPLE'), ('grey', 'GREY'), ('white', 'WHITE'), ('warth', 'EARTH'), ('other', 'OTHER')], default='', max_length=6, verbose_name='Gear Tape Colour 2'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tape_colour_3',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('red', 'RED'), ('orange', 'ORANGE'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('purple', 'PURPLE'), ('grey', 'GREY'), ('white', 'WHITE'), ('warth', 'EARTH'), ('other', 'OTHER')], default='', max_length=6, verbose_name='Gear Tape Colour 3'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='60ede9cd7db34857ac5b1f93159828e5', max_length=32),
        ),
    ]
