# Generated by Django 2.2.3 on 2019-08-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0015_auto_20190817_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(choices=[('member', 'MEMBER'), ('president', 'PRESIDENT'), ('senior_treasurer', 'SENIOR TREASURER'), ('junior_treasurer', 'JUNIOR TREASURER'), ('secretary', 'SECRETARY'), ('tackle_master', 'TACKLE MASTER'), ('meets_secretary', 'MEETS SECRETARY'), ('social_secretary', 'SOCIAL SECRETARY')], default='Member', max_length=30, verbose_name='Club Position'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='62d22849d8634e89bb8fbaba3b39270e', max_length=32),
        ),
    ]
