# Generated by Django 2.2.4 on 2019-08-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0017_auto_20190817_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rank',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.ManyToManyField(to='UserPortal.Rank', verbose_name='Club Position'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='e42a0d5820a545a0988de57b7b71e908', max_length=32),
        ),
    ]
