# Generated by Django 2.2.4 on 2019-08-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0018_auto_20190817_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='607f584e3ae34306bbc42beb16aee422', max_length=32),
        ),
    ]
