# Generated by Django 2.2.4 on 2019-08-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0020_auto_20190817_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='3a1470dc83d746c5910ce460a4906007', max_length=32),
        ),
    ]
