# Generated by Django 2.2.4 on 2019-08-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0021_auto_20190817_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='7131f4f24dc3483195946685f2069d05', max_length=32),
        ),
    ]
