# Generated by Django 2.2.4 on 2019-08-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0022_auto_20190817_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('user_key', models.CharField(default='50ebd4bd5a7c4a1d98e88ba218607a03', max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('college', models.CharField(blank=True, max_length=50)),
                ('tape_colour_1', models.CharField(blank=True, choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('red', 'RED'), ('orange', 'ORANGE'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('purple', 'PURPLE'), ('grey', 'GREY'), ('white', 'WHITE'), ('warth', 'EARTH'), ('other', 'OTHER')], default='', max_length=6, verbose_name='Gear Tape Colour 1')),
                ('tape_colour_2', models.CharField(blank=True, choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('red', 'RED'), ('orange', 'ORANGE'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('purple', 'PURPLE'), ('grey', 'GREY'), ('white', 'WHITE'), ('warth', 'EARTH'), ('other', 'OTHER')], default='', max_length=6, verbose_name='Gear Tape Colour 2')),
                ('tape_colour_3', models.CharField(blank=True, choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('red', 'RED'), ('orange', 'ORANGE'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('purple', 'PURPLE'), ('grey', 'GREY'), ('white', 'WHITE'), ('warth', 'EARTH'), ('other', 'OTHER')], default='', max_length=6, verbose_name='Gear Tape Colour 3')),
                ('tape_colour_notes', models.CharField(blank=True, max_length=50, verbose_name='Gear Tape Notes')),
                ('status', models.CharField(choices=[('Frequent', 'Active - Frequent'), ('Infrequent', 'Active - Infrequent'), ('Expo', 'Active - Expo'), ('Inactive', 'Inactive')], default='Inactive', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='6ff511ee8ba14cfbb69d9f9d63e4251e', max_length=32),
        ),
    ]
