# Generated by Django 2.2.4 on 2019-08-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0023_auto_20190817_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legacyuser',
            name='user_key',
        ),
        migrations.RemoveField(
            model_name='legacyuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='6cc00553ab424c198b669769dd06709e', max_length=32),
        ),
    ]
