# Generated by Django 2.2.4 on 2019-08-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0025_auto_20190817_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyuser',
            name='rank',
            field=models.ManyToManyField(to='UserPortal.Rank', verbose_name='Club Position'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='03e05697898b4dafba601a5db0b29f3c', max_length=32),
        ),
    ]
