# Generated by Django 2.2.4 on 2019-08-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0026_auto_20190817_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='92f48acfd1dd477c8de60a42522cc246', max_length=32),
        ),
    ]
