# Generated by Django 2.2.4 on 2019-08-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0027_auto_20190817_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='committee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rank',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='ff0df4f8ad55499493c88e9927ab919b', max_length=32),
        ),
    ]
