# Generated by Django 2.2.4 on 2019-08-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0028_auto_20190817_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('president', models.CharField(blank=True, max_length=20)),
                ('senior_treasurer', models.CharField(blank=True, max_length=20)),
                ('junior_treasurer', models.CharField(blank=True, max_length=20)),
                ('secretary', models.CharField(blank=True, max_length=20)),
                ('tackle_master', models.CharField(blank=True, max_length=20)),
                ('social_secretary', models.CharField(blank=True, max_length=20)),
                ('training_secretary', models.CharField(blank=True, max_length=20)),
                ('webmaster', models.CharField(blank=True, max_length=20)),
                ('librarian', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='ec3a90b2a2de481d8ecaa985d10d0cbf', max_length=32),
        ),
    ]
