# Generated by Django 2.2.4 on 2019-08-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0030_auto_20190817_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='lamp_post',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='7dc2eb69193b49f9b770b84ed7c39c0d', max_length=32),
        ),
    ]
