# Generated by Django 2.2.4 on 2019-08-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0031_auto_20190817_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='73fcf2f455aa4d509f37647f8ead8eda', max_length=32),
        ),
    ]
