# Generated by Django 2.2.4 on 2019-08-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0032_auto_20190817_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='junior_treasurer',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='lamp_post',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='librarian',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='meets_secretary',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='president',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='secretary',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='senior_treasurer',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='social_secretary',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='tackle_master',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='training_secretary',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='webmaster',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='efc516c5e7fa4add8595df3d1eaa5ee7', max_length=32),
        ),
    ]
