# Generated by Django 2.2.4 on 2019-08-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0033_auto_20190817_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='361a6e5354df4d35b92555de5d33f392', max_length=32),
        ),
    ]
