# Generated by Django 2.2.3 on 2019-08-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0034_auto_20190817_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='4f55286f870e4857b727f8ba32b8d673', max_length=32),
        ),
    ]
