# Generated by Django 2.2.4 on 2019-08-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0037_auto_20190820_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_human',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='6381819fc9084cf38a3d14cffffc0cde', max_length=32),
        ),
    ]
