# Generated by Django 2.2.4 on 2019-08-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0037_auto_20190820_1643'),
        ('UserPortal', '0037_auto_20190819_2200'),
    ]

    operations = [
    ]
