# Generated by Django 2.2.4 on 2019-08-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0037_auto_20190820_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_human',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='6f2d97ba4382443199a60ce57ee66b1b', editable=False, max_length=32),
        ),
    ]
