# Generated by Django 2.2.4 on 2019-08-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0038_merge_20190820_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='3c64890263b64c99b71d1a1d0939af05', max_length=32),
        ),
    ]
