# Generated by Django 2.2.4 on 2019-08-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0039_auto_20190822_1548'),
        ('UserPortal', '0039_auto_20190821_1507'),
    ]

    operations = [
    ]
