# Generated by Django 2.2.4 on 2019-08-29 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0040_merge_20190829_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
