# Generated by Django 2.2.4 on 2019-08-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0040_merge_20190830_0853'),
        ('UserPortal', '0041_auto_20190829_1345'),
    ]

    operations = [
    ]
