# Generated by Django 2.2 on 2020-02-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200115_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='directory',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
