# Generated by Django 2.2 on 2020-02-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20200224_2111'),
        ('Blog', '0004_auto_20200210_2022'),
    ]

    operations = [
    ]
