# Generated by Django 2.2 on 2020-03-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_merge_20200225_1853'),
        ('Blog', '0006_auto_20200317_1427'),
    ]

    operations = [
    ]
