# Generated by Django 2.2.3 on 2019-08-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20190818_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Image',
            new_name='Images',
        ),
    ]
