# Generated by Django 2.2 on 2020-03-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_merge_20200317_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='attendees_wo_accounts',
            new_name='attendees_wo_account',
        ),
        migrations.AlterField(
            model_name='trip',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.Album'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='posts',
            field=models.ManyToManyField(blank=True, to='Blog.Post'),
        ),
    ]
