# Generated by Django 2.2 on 2020-03-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20200317_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='attendees_wo_account',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='attendees',
        ),
        migrations.AddField(
            model_name='trip',
            name='attendees',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='leader',
            field=models.CharField(max_length=200),
        ),
    ]
