# Generated by Django 2.2.3 on 2019-08-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20190818_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Images',
            new_name='images',
        ),
    ]
