# Generated by Django 2.2 on 2020-03-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20200318_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='days',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='trip',
            name='attendees',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
