# Generated by Django 2.2.3 on 2019-08-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_auto_20190818_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Caving', 'Caving'), ('Training', 'Training'), ('Social', 'Social')], default='Caving', max_length=10),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
