# Generated by Django 2.2.4 on 2020-03-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='trip',
            name='attendees',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
