# Generated by Django 2.2.4 on 2019-08-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_auto_20190818_1503'),
        ('Blog', '0013_auto_20190818_2213'),
    ]

    operations = [
    ]
