# Generated by Django 2.2 on 2020-03-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_auto_20200321_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
