# Generated by Django 2.2.4 on 2019-08-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_auto_20190820_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='Blog.Image'),
        ),
    ]
