# Generated by Django 2.2.4 on 2019-08-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_merge_20190818_2232'),
        ('Blog', '0017_auto_20190820_1707'),
    ]

    operations = [
    ]
