# Generated by Django 2.2 on 2020-03-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_expo',
            field=models.BooleanField(default=False),
        ),
    ]
