# Generated by Django 2.2 on 2020-03-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_auto_20200322_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
